import { Project } from './types'

export const projects: Project[] = [
  {
    id: 'moodmixer',
    name: 'MoodMixer',
    creator: 'Maya Chen',
    creatorAvatar: 'MC',
    description: 'An AI-powered mood-based playlist generator that creates the perfect soundtrack for your current vibe. Select your mood and watch as beautiful visualizations dance to your generated playlist.',
    shortDescription: 'AI playlist generator based on your mood',
    category: 'Creative',
    gradient: 'from-purple-500 via-pink-500 to-red-500',
    accentColor: '#ec4899',
    icon: '🎵',
    tags: ['Music', 'AI', 'Visualization'],
  },
  {
    id: 'pixelpets',
    name: 'PixelPets',
    creator: 'Jake Rodriguez',
    creatorAvatar: 'JR',
    description: 'A nostalgic virtual pet game with modern twist. Feed, play, and care for your pixel companion. Each pet has unique personality traits and evolves based on how you treat them!',
    shortDescription: 'Retro virtual pet with modern vibes',
    category: 'Game',
    gradient: 'from-green-400 via-cyan-500 to-blue-500',
    accentColor: '#22d3ee',
    icon: '🐾',
    tags: ['Game', 'Retro', 'Interactive'],
  },
  {
    id: 'studybuddy',
    name: 'StudyBuddy',
    creator: 'Priya Sharma',
    creatorAvatar: 'PS',
    description: 'Smart flashcard app that adapts to your learning style. Uses spaced repetition and tracks your progress with beautiful analytics. Study smarter, not harder!',
    shortDescription: 'AI flashcards that adapt to you',
    category: 'Education',
    gradient: 'from-amber-400 via-orange-500 to-red-500',
    accentColor: '#f97316',
    icon: '📚',
    tags: ['Education', 'AI', 'Productivity'],
  },
  {
    id: 'budgetboba',
    name: 'BudgetBoba',
    creator: 'Kevin Wu',
    creatorAvatar: 'KW',
    description: 'Track your spending with this boba-themed budget app! Every expense category is a different boba flavor. Watch your savings grow like pearls in your drink.',
    shortDescription: 'Budget tracking with boba vibes',
    category: 'Productivity',
    gradient: 'from-amber-300 via-yellow-400 to-amber-500',
    accentColor: '#fbbf24',
    icon: '🧋',
    tags: ['Finance', 'Fun', 'Tracking'],
  },
  {
    id: 'vibecam',
    name: 'VibeCam',
    creator: 'Zara Johnson',
    creatorAvatar: 'ZJ',
    description: 'Wild photo filters that detect the vibe and add the perfect effects. From "main character energy" to "corporate dystopia", find the filter that matches your aesthetic.',
    shortDescription: 'Chaotic good photo filters',
    category: 'Creative',
    gradient: 'from-fuchsia-500 via-purple-600 to-indigo-600',
    accentColor: '#a855f7',
    icon: '📸',
    tags: ['Photos', 'Filters', 'Chaos'],
  },
  {
    id: 'codepoetry',
    name: 'CodePoetry',
    creator: 'Alex Okonkwo',
    creatorAvatar: 'AO',
    description: 'Transform your code into beautiful poetry. Watch as your functions become verses and your variables become metaphors. Code is art, and this proves it.',
    shortDescription: 'Turn code into beautiful poetry',
    category: 'Quirky',
    gradient: 'from-slate-400 via-zinc-500 to-neutral-600',
    accentColor: '#71717a',
    icon: '✨',
    tags: ['Art', 'Code', 'Poetry'],
  },
  {
    id: 'groupsync',
    name: 'GroupSync',
    creator: 'Emma Nakamura',
    creatorAvatar: 'EN',
    description: 'Finally, a study group coordinator that works! Vote on meeting times, share resources, and chat in real-time. No more "when2meet" chaos.',
    shortDescription: 'Study group scheduling made easy',
    category: 'Social',
    gradient: 'from-blue-500 via-indigo-500 to-purple-600',
    accentColor: '#6366f1',
    icon: '👥',
    tags: ['Social', 'Planning', 'Groups'],
  },
  {
    id: 'neuraldoodle',
    name: 'NeuralDoodle',
    creator: 'Marcus Lee',
    creatorAvatar: 'ML',
    description: 'Draw anything and watch AI complete your doodle in real-time. From rough sketches to stunning art, see your imagination come to life with neural magic.',
    shortDescription: 'AI that completes your doodles',
    category: 'Technical',
    gradient: 'from-emerald-400 via-teal-500 to-cyan-600',
    accentColor: '#14b8a6',
    icon: '🎨',
    tags: ['AI', 'Art', 'Canvas'],
  },
]
